- name: tear down existing services
  community.docker.docker_compose_v2:
    project_src: /etc/docker/wg-easy
    state: absent

- name: start the service again
  community.docker.docker_compose_v2:
    project_src: /etc/docker/wg-easy
    wait: true
    wait_timeout: 300
