networks:
  proxy:
    external: true


services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    environment:
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
    labels:
      traefik.enable: true
      traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: "https"
      traefik.http.routers.traefik.entrypoints: "http"
      traefik.http.routers.traefik.rule: "Host(`traefik.homedns.pro`)"
      traefik.http.routers.traefik.middlewares: "traefik-https-redirect"
      traefik.http.routers.traefik-secure.entrypoints: "https"
      traefik.http.routers.traefik-secure.rule: "Host(`traefik.homedns.pro`)"
      traefik.http.routers.traefik-secure.middlewares: "traefik-keycloak@file"
      traefik.http.routers.traefik-secure.tls: true
      traefik.http.routers.traefik-secure.tls.certresolver: "porkbun"
      traefik.http.routers.traefik-secure.tls.domains[0].main: "homedns.pro"
      traefik.http.routers.traefik-secure.tls.domains[0].sans: "*.homedns.pro"
      traefik.http.routers.traefik-secure.tls.domains[1].main: "proxmox.homedns.pro"
      traefik.http.routers.traefik-secure.tls.domains[1].sans: "*.proxmox.homedns.pro"
      traefik.http.routers.traefik-secure.service: "api@internal"
