- name: remove-previous-debian-template
  ansible.builtin.shell: qm destroy 100200

- name: create-new-debian-template
  ansible.builtin.shell: /root/create-debian12-template.sh

- name: re-create-new-open-id-realm
  ansible.builtin.shell: /root/create-openid-realm.sh
