- name: remove-previous-debian-template
  ansible.builtin.shell: /root/delete-bookworm-template.sh

- name: create-new-debian-template
  ansible.builtin.shell: /root/create-bookworm-template.sh

- name: remove-previous-home-assistant-template
  ansible.builtin.shell: /root/delete-home-assistant-template.sh

- name: create-new-home-assistant-template
  ansible.builtin.shell: /root/create-home-assistant-template.sh
