- name: install pre-requisites
  ansible.builtin.apt:
    name:
      - gpg
      - ca-certificates
      - apt-transport-https
    state: latest

- name: add repository
  ansible.builtin.deb822_repository:
    name: ubiquiti
    types: deb
    uris: "https://www.ui.com/downloads/unifi/{{ ansible_distribution | lower }}"
    suites: "stable"
    components: ubiquiti
    architectures: "{{ normalized_arch }}"
    inrelease_path: "InRelease"
    signed_by: "https://dl.ui.com/unifi/unifi-repo.gpg"
    state: present

- name: install unifi controller
  ansible.builtin.apt:
    name:
      - unifi
    state: latest
    update_cache: true

- name: ensure service is running
  ansible.builtin.service:
    name: unifi
    state: started
    enabled: true

- name: give backup user access to config backups
  ansible.builtin.user:
    name: "{{ backup_user }}"
    groups: unifi
    append: yes
