---
private_key_file: ~/.ssh/ansible
ansible_ssh_user: sujoy
ssh_authorized_public_keys:
  - "{{ vault_asgard_wsl_ssh_key }}"
  - "{{ vault_asgard_ssh_key }}"
install_packages:
  - tree
  - python3
  - vim
  - cron
  - iperf3
