---
private_key_file: ~/.ssh/ansible
ansible_ssh_user: sujoy
ssh_authorized_public_keys:
  - "{{ vault_wakanda_ssh_key }}"
  - "{{ vault_asgard_wsl_ssh_key }}"
  - "{{ vault_asgard_ssh_key }}"
ssh_authorized_keys_exclusive: true
  
install_packages:
  - tree
  - python3
  - vim
  - cron
  - iperf3
  - rsync
  - dnsutils
