---
ansible_ssh_user: root
ssh_authorized_keys_exclusive: false
ssh_permit_root_login: prohibit-password

open_id:
  realm: "{{gvault.open_id.realm}}"
  issuer_url: "{{gvault.open_id.issuer_url}}"
  user:
    email: "{{gvault.open_id.user.email}}"
  client_id: "{{gvault.open_id.client_id}}"
  client_key: "{{gvault.open_id.client_key}}"

install_packages:
  - jq
  - tree
  - vim
  - cron
  - iperf3
  - rsync
  - dnsutils

bookworm:
  user: "{{gvault.bookworm.user}}"
  passwd: "{{gvault.bookworm.user_passwd}}"
  groups:
    - wheel
    - sudo
    - adm
    - netdev
    - plugdev
    - systemd-journal
