#cloud-config
timezone: ${var.config.timezone}
users:
  - name: ${var.config.username}
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${trimspace(data.local_file.ssh_public_key.content)}
    sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
packages:
  - qemu-guest-agent
  - net-tools
  - curl
disable_root: true
ssh_deletekeys: true
ssh_genkeytypes: [ed25519]

runcmd:
  - systemctl enable --now qemu-guest-agent
  - echo "done" > /tmp/cloud-config.done
