networks:
  reverse_proxy:
    driver: bridge
    
services:
  reverse_proxy:
    image: caddy-porkbun:2.9
    build: .
    container_name: caddy_reverse_proxy
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
