file-browser:
  root: /app/data

server:
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https

spring:
  security:
    oauth2:
      client:
        registration:
          file-browser:
            provider: file-browser
            client-id: {{vault_ftp.client_id}}
            client-secret: {{vault_ftp.client_key}}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          file-browser:
            issuer-uri: "{{vault_ftp.issuer_uri}}"
