- name: Update apt repository cache
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400 #one day

- name: Upgrade all packages on servers
  ansible.builtin.apt:
    upgrade: dist

- name: install packages
  ansible.builtin.apt:
    name: "{{ install_packages }}"
    state: latest
