- name: allow release info change
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/99-release_info_change
    state: present
    create: yes
    line: Acquire::AllowReleaseInfoChange::Codename "true";
  when: allow_release_info_change

- name: Update apt repository cache
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400 #one day

- name: Upgrade all packages on servers
  ansible.builtin.apt:
    upgrade: full

- name: install packages
  ansible.builtin.apt:
    name: "{{ install_packages }}"
    state: latest

- name: check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: reboot_required_file.stat.exists == true
