- name: add setup config file
  ansible.builtin.copy:
    src: wg-easy/
    dest: /etc/docker/wg-easy
    owner: root
    group: root
    mode: "600"
  notify:
    - tear down existing services
    - start the service again

- name: copy environment file
  ansible.builtin.template:
    src: "{{item}}"
    dest: "/etc/docker/wg-easy/{{item}}"
    owner: root
    group: root
    mode: "600"
  loop:
    - ".env"
  notify:
    - tear down existing services
    - start the service again
