- name: add proxmox setup scripts
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/root/{{item}}"
    mode: "u+rwx"
  loop:
    - "terraform-user.sh"
    - "setup-repositories.sh"

- name: add create template scripts
  ansible.builtin.copy:
    src: create-debian12-template.sh
    dest: "/root/"
    mode: "u+rwx"
  notify:
    - remove-previous-debian-template
    - create-new-debian-template

- name: setup repositories
  ansible.builtin.shell: /root/setup-repositories.sh
  changed_when: false

- name: add realm setup scripts
  ansible.builtin.template:
    src: create-openid-realm.sh
    dest: /root/
    owner: root
    group: root
    mode: u+rwx
  notify:
    - re-create-new-open-id-realm
