- name: remove enterprise repositories
  ansible.builtin.deb822_repository:
    name: pve-enterprise
    types: deb
    uris: https://enterprise.proxmox.com/debian/pve
    suites: "{{ ansible_distribution_release }}"
    signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg
    enabled: false
    components:
      - pve-enterprise

- name: add no-subscription pve repository
  ansible.builtin.deb822_repository:
    name: pve-no-subscription
    types: deb
    uris: http://download.proxmox.com/debian/pve/
    suites: "{{ ansible_distribution_release }}"
    signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg
    state: "present"
    components:
      - pve-no-subscription

- name: add no-subscription ceph repository
  ansible.builtin.deb822_repository:
    name: ceph-no-subscription
    types: deb
    uris: http://download.proxmox.com/debian/ceph-squid/
    suites: "{{ ansible_distribution_release }}"
    signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg
    state: "present"
    components:
      - no-subscription

- name: add non-free-firmware component to apt sources
  ansible.builtin.deb822_repository:
    name: debian
    types: deb
    uris: http://deb.debian.org/debian
    suites: "{{ ansible_distribution_release }}"
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: "present"
    components:
      - main
      - contrib
      - non-free-firmware

- name: add security repo
  ansible.builtin.deb822_repository:
    name: debian-security
    types: deb
    uris: http://security.debian.org/
    suites: "{{ ansible_distribution_release }}-security"
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: "present"
    components:
      - main
      - contrib
      - non-free-firmware

- name: add non-free-firmware component to apt updates
  ansible.builtin.deb822_repository:
    name: debian-updates
    types: deb
    uris: http://deb.debian.org/debian
    suites: "{{ ansible_distribution_release }}-updates"
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: "present"
    components:
      - main
      - contrib
      - non-free-firmware

- name: update apt repository cache
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400 #one day

- name: install packages
  ansible.builtin.apt:
    name:
      - intel-microcode
    state: latest

- name: generate ed25519 keys for root
  ansible.builtin.openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519
    state: present
    owner: root
    group: root
