- name: remove enterprise repositories
  ansible.builtin.apt_repository:
    repo: "{{item}}"
    state: absent
    update_cache: false
  loop:
    - "deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise"
    - "deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise"

- name: add no-subscription repositories
  ansible.builtin.apt_repository:
    repo: "{{item}}"
    state: present
    filename: no-subscription
    update_cache: false
  loop:
    - "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    - "deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription"

- name: update apt repository cache
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400 #one day
    
- name: generate ed25519 keys for root
  ansible.builtin.openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519
    state: present
    owner: root
    group: root
