---
- name: install required packages
  ansible.builtin.apt:
    name:
      - gpg
    state: latest

- name: add docker gpg apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3
      - python3-docker
    state: present
    update_cache: true

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: add user to docker group
  user:
    name: "{{ansible_ssh_user}}"
    groups: "docker"
    append: yes
