---
- name: install required packages
  ansible.builtin.apt:
    name:
      - gpg
    state: latest

- name: add repository into sources list
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_lsb.codename }}"
    components: stable
    architectures: "{{ normalized_arch }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3
      - python3-docker
    state: present
    update_cache: true

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: add user to docker group
  user:
    name: "{{ansible_ssh_user}}"
    groups: "docker"
    append: yes
