---
- hosts: caserver
  become: no
  gather_facts: no
  pre_tasks:
    - name: setup known hosts
      ansible.builtin.include_role:
        name: user_settings
        tasks_from: ssh_setup
      vars:
        ansible_hostname: "{{inventory_hostname}}"
        add_known_host_for_ip: false

- hosts: caserver
  become: yes
  roles:
    - system
    - security

- hosts: caserver
  become: no
  roles:
    - user_settings