---
- hosts: pi
  become: false
  gather_facts: false
  pre_tasks:
    - name: setup known hosts
      ansible.builtin.include_role:
        name: system
        tasks_from: ssh_setup
      vars:
        ansible_hostname: "{{inventory_hostname}}"
        add_known_host_for_ip: false

- hosts: pi
  become: false
  roles:
    - system
