---
- hosts: proxmox
  become: no
  gather_facts: no
  pre_tasks:
    - name: setup known hosts
      ansible.builtin.include_role:
        name: system
        tasks_from: ssh_setup
      vars:
        ansible_hostname: "{{inventory_hostname}}"
        add_known_host_for_ip: false

        
# the specific host does not matter, just that cluster config is executed on one node only
- hosts: pve1
  become: no
  roles:
    - proxmox_cluster
        
- hosts: proxmox
  become: no
  roles:
    - proxmox_init
    - system

