- hosts: all
  tasks:
    - name: Print all variables
      debug:
        var: to_debug
      vars:
        to_debug:
          - "{{ ansible_os_family }}"
          - "{{ ansible_architecture }}"
          - "{{ ansible_distribution }}"
          - "{{ distro.ssh_service_name[ansible_distribution] }}"
