---
- hosts: vm
  become: no
  gather_facts: no
  pre_tasks:
    - name: setup known hosts
      ansible.builtin.include_role:
        name: system
        tasks_from: ssh_setup
      vars:
        ansible_hostname: "{{inventory_hostname}}"
        add_known_host_for_ip: false
  tags:
    - always

- hosts: vm
  roles:
    - system
    - docker
  tags:
    - always
    - system

- hosts: sundarban
  become: yes
  roles:
    - traefik
    - ddns
    - wireguard
    - unifi

- hosts: gorumara
  become: yes
  roles:
    - keycloak
  tags:
    - keycloak

