---
- hosts: vm
  become: no
  gather_facts: no
  pre_tasks:
    - name: setup known hosts
      ansible.builtin.include_role:
        name: system
        tasks_from: ssh_setup
      vars:
        ansible_hostname: "{{inventory_hostname}}"
        add_known_host_for_ip: false
  tags:
    - always

- hosts: vm
  roles:
    - system
  tags:
    - always
    - system

- hosts: network_tools
  become: yes
  roles:
    - docker
    - traefik
    - ddns

- hosts: authentication
  become: yes
  roles:
    - docker
    - keycloak

- hosts: vpn
  become: yes
  roles:
    - role: wireguard
      tags:
        - vpn
    - role: unifi
      tags:
        - unifi
    
