#cloud-config

fqdn: ${config.name}.${config.searchdomain}
hostname: ${config.name}
prefer_fqdn_over_hostname: true

timezone: ${config.timezone}

users:
  - name: ${config.username}
    uid: ${config.user_id}
    groups:
      - sudo
    shell: /bin/bash
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - qemu-guest-agent
  - ansible
  - git

disable_root: true
ssh_deletekeys: true
ssh_genkeytypes: [ed25519]

manage_resolv_conf: true
resolv_conf:
  searchdomains: [${config.searchdomain}]

write_files:
  - path: /etc/ssh-keysigner/config.yml
    owner: root:root
    permissions: '0400'
    content: |
      ca_server_url: ${ca_server_url}
      client_id: ${ca_sso_client_id}
      client_secret: ${ca_sso_client_secret}
      token_url: ${ca_sso_token_url}
  - path: /etc/ssh/user_ca.pub
    owner: root:root
    permissions: '0400'
    content: |
      ${ca_user_public_key}
  - path: /etc/ssh/sshd_config.d/01_trusted_user_ca.conf
    owner: root:root
    permissions: '0400'
    content: |
      TrustedUserCAKeys /etc/ssh/user_ca.pub

runcmd:
  - systemctl enable --now qemu-guest-agent
  - groupmod -g ${config.user_id} ${config.username}
  - ansible-pull -U https://github.com/binarycodes/homelab-self-provisioner.git debian.yml
  - ansible-pull -U https://github.com/binarycodes/homelab-self-provisioner.git kubernetes.yml
  - echo "done" > /tmp/cloud-config.done
