#cloud-config
timezone: ${config.timezone}
users:
  - name: ${config.username}
    uid: ${config.user_id}
    groups:
      - sudo
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_keys}
    sudo: ALL=(ALL) NOPASSWD:ALL

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - qemu-guest-agent
  - ansible
  - git

disable_root: true
ssh_deletekeys: true
ssh_genkeytypes: [ed25519]

manage_resolv_conf: true
resolv_conf:
  searchdomains: [${config.searchdomain}]

runcmd:
  - systemctl enable --now qemu-guest-agent
  - groupmod -g ${config.user_id} ${config.username}
  - ansible-pull -U https://github.com/binarycodes/homelab-self-provisioner.git debian.yml
  - ansible-pull -U https://github.com/binarycodes/homelab-self-provisioner.git kubernetes.yml
  - echo "done" > /tmp/cloud-config.done
