- name: create export path
  ansible.builtin.file:
    path: /etc/docker/keycloak/export
    state: directory
    owner: 1000
    mode: '0755'

- block:
    - name: find previous exported files
      ansible.builtin.find:
        paths: /etc/docker/keycloak/export/
        file_type: file
        patterns: "*.json"
      register: files_to_delete

    - name: remove previous files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
    
    
- name: shutdown keycloak service
  community.docker.docker_compose_v2:
    project_src: /etc/docker/keycloak
    services: keycloak
    state: absent

- name: start the keycloak backup service
  community.docker.docker_compose_v2:
    project_src: /etc/docker/keycloak
    services: keycloak-export
    state: present

- name: wait for backup to complete
  ansible.builtin.wait_for:
    path: /etc/docker/keycloak/export/homelab-realm.json
    state: present
    timeout: 300
    
- name: fetch the realm export and put it into keycloak config location
  ansible.builtin.fetch:
    src: /etc/docker/keycloak/export/homelab-realm.json
    dest: "{{ playbook_dir }}/backup/homelab-realm.json"
    flat: true
    fail_on_missing: true

- name: restart keycloak service
  community.docker.docker_compose_v2:
    project_src: /etc/docker/keycloak
    services: keycloak
    state: present
    wait: true
    wait_timeout: 300
    
