- name: disable password login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(#\s*)?PasswordAuthentication\s+yes\s*$'
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  notify: restart sshd

- name: prohibit password for root login (no keyboard interactive)
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#\s*)?PermitRootLogin.*'
    line: "PermitRootLogin {{ ssh_permit_root_login }}"
    state: present
    backup: yes
  notify: restart sshd

- name: prohibit X11 forwarding
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#\s)*?X11Forwarding.*'
    line: "X11Forwarding no"
    state: present
    backup: yes
  notify: restart sshd

- name: restrict accepted server ssh keys
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/00_accepted_public_key_types.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      PubkeyAcceptedKeyTypes ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
      HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
  notify: restart sshd
