- name: restart the service again
  block:
    - name: restart docker
      community.docker.docker_compose_v2:
        project_src: /etc/docker/jellyfin
        wait: true
        wait_timeout: 300
        state: present

    - name: restart docker
      community.docker.docker_compose_v2:
        project_src: /etc/docker/jellyfin
        wait: true
        wait_timeout: 300
        state: restarted
