---
- hosts: all
  become: no
  gather_facts: no
  pre_tasks:
    - name: Check known_hosts for {{ inventory_hostname }}
      local_action: shell ssh-keygen -F {{ inventory_hostname }}
      register: has_entry_in_known_hosts_file
      changed_when: false
      ignore_errors: true
    - name: Add host key for {{ inventory_hostname }} on first run
      when: has_entry_in_known_hosts_file.rc == 1
      local_action: shell ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts

- hosts: all
  become: yes
  pre_tasks:
    - name: update repository cache
      package:
        update_cache: yes

- hosts: apt_based
  become: yes
  roles:
    - apt_packages

- hosts: all
  become: yes
  roles:
    - base

- hosts: networks_apps
  become: yes
  roles:
    - pihole
    - pivpn
    - ddns
